"""002_failure_columns_and_indexes

Revision ID: b756d62b0781
Revises: d99e0c4aa5df
Create Date: 2026-09-25 18:37:47.354675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b756d62b0781'
down_revision: Union[str, None] = 'd99e0c4aa5df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_datasets_project_id'), 'datasets', ['project_id'], unique=False)
    op.create_index(op.f('ix_metric_results_trace_id'), 'metric_results', ['trace_id'], unique=False)
    op.add_column('runs', sa.Column('failure_reason', sa.Text(), nullable=True))
    op.add_column('runs', sa.Column('failure_type', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_runs_dataset_id'), 'runs', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_runs_project_id'), 'runs', ['project_id'], unique=False)
    op.create_index(op.f('ix_traces_run_id'), 'traces', ['run_id'], unique=False)
    op.create_index(op.f('ix_traces_test_case_id'), 'traces', ['test_case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_traces_test_case_id'), table_name='traces')
    op.drop_index(op.f('ix_traces_run_id'), table_name='traces')
    op.drop_index(op.f('ix_runs_project_id'), table_name='runs')
    op.drop_index(op.f('ix_runs_dataset_id'), table_name='runs')
    op.drop_column('runs', 'failure_type')
    op.drop_column('runs', 'failure_reason')
    op.drop_index(op.f('ix_metric_results_trace_id'), table_name='metric_results')
    op.drop_index(op.f('ix_datasets_project_id'), table_name='datasets')
    # ### end Alembic commands ###
